name: Feature request
description: Suggest an improvement for the Linux-native editor.
title: "[Feature] <short summary>"
labels: ["type:enhancement", "area:linux"]
body:
- type: checkboxes
  attributes:
    label: Pre-flight checks
    options:
    - label: I searched existing issues and did not find a duplicate request.
      required: true
- type: textarea
  attributes:
    label: Problem statement
    description: What workflow or pain point should be improved?
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed solution
    description: What behavior, UI, or API change do you want?
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives considered
    description: Other options you evaluated and why they are less suitable.
  validations:
    required: false
- type: textarea
  attributes:
    label: User impact
    description: Who benefits and how often this would be used.
  validations:
    required: true
- type: textarea
  attributes:
    label: Compatibility and performance considerations
    description: Any known constraints (distro/desktop behavior, extension compatibility, perf impact).
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment (if relevant)
    description: Include distro, kernel, desktop environment/window manager, and app version.
    placeholder: |
      Distro: Manjaro / Arch / Ubuntu / Fedora
      Kernel: 6.x
      Desktop: KDE / GNOME / Xfce / sway
      App version: v0.9.9-rc.3a
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Links, screenshots, mockups, or related issues.
  validations:
    required: false
